# Rubric Service Docker Compose
# Run with: docker compose up
# Or from root: docker compose up rubric-service

version: '3.8'

services:
  rubric-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peerit-rubric-service
    environment:
      # Service Configuration
      - PORT=3023
      - NODE_ENV=development
      
      # Database Configuration (isolated database)
      - DATABASE_URL=postgresql://peerit:peerit_dev@postgres:5432/peerit_rubrics
      
      # Authentication
      - JWT_SECRET=auth_service_jwt_secret_change_in_production
      - AUTH_SERVICE_URL=http://auth-service:3020
      
      # File Storage (for rubric templates)
      - UPLOAD_PATH=/app/uploads
      - MAX_FILE_SIZE=5MB
    ports:
      - "3023:3023"
    networks:
      - peerit-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3023/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    volumes:
      - rubric_uploads:/app/uploads

volumes:
  rubric_uploads:
    driver: local

# Import shared infrastructure
networks:
  peerit-network:
    external: true
