# Review Service Docker Compose
# Run with: docker compose up
# Or from root: docker compose up review-service

version: '3.8'

services:
  review-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peerit-review-service
    environment:
      # Service Configuration
      - PORT=3024
      - NODE_ENV=development
      
      # Database Configuration (isolated database)
      - DATABASE_URL=postgresql://peerit:peerit_dev@postgres:5432/peerit_reviews
      
      # Redis Configuration (for temporary review data)
      - REDIS_URL=redis://redis:6379/3
      
      # Authentication
      - JWT_SECRET=auth_service_jwt_secret_change_in_production
      - AUTH_SERVICE_URL=http://auth-service:3020
      
      # Service Dependencies
      - TEAM_SERVICE_URL=http://team-service:3022
      - RUBRIC_SERVICE_URL=http://rubric-service:3023
      - EMAIL_SERVICE_URL=http://email-service:3026
      
      # Review Configuration
      - REVIEW_TIMEOUT_HOURS=72
      - AUTO_REMINDER_HOURS=24
    ports:
      - "3024:3024"
    networks:
      - peerit-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3024/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

# Import shared infrastructure
networks:
  peerit-network:
    external: true
