services:
  keycloak:
    image: ghcr.io/pxl-digital-application-samples/peerit-keycloak:latest
    container_name: keycloak
    hostname: keycloak
    environment:
      # Database Configuration
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5433/peerit_test
      KC_DB_USERNAME: testuser
      KC_DB_PASSWORD: testpass
      
      # Development Configuration
      KC_HOSTNAME: localhost
      KC_HTTP_PORT: 8080
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      
      # Logging
      KC_LOG_LEVEL: INFO
      
    ports:
      - "8080:8080"
    # No volumes needed - realm config and themes are built into the image
    command: 
      - start-dev
      - --import-realm
    depends_on: []
    networks:
      - peerit-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/realms/master"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  keycloak-postgres-data:
    driver: local

networks:
  peerit-network:
    external: true
