# Infrastructure Services - Shared Database and Cache
# This file contains shared infrastructure that services depend on
# Run with: docker compose -f infra/docker/compose.yml up

version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: peerit-postgres
    environment:
      POSTGRES_USER: peerit
      POSTGRES_PASSWORD: peerit_dev
      POSTGRES_DB: peerit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
    networks:
      - peerit-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U peerit"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: peerit-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - peerit-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: Database administration tool
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: peerit-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@peerit.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - peerit-network
    profiles:
      - tools

  # Optional: Redis administration tool
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: peerit-redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - peerit-network
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  peerit-network:
    driver: bridge
    name: peerit-network
