services:
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-peerit_test}
      POSTGRES_USER: ${POSTGRES_USER:-testuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-testpass}
    ports:
      - "${POSTGRES_PORT:-5434}:5432"
    command: postgres -c 'max_connections=100' -c 'shared_buffers=128MB'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-testuser} -d ${POSTGRES_DB:-peerit_test}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-test:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6381}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  keycloak-test:
    image: ${KEYCLOAK_IMAGE:-ghcr.io/pxl-digital-application-samples/peerit-keycloak:latest}
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USER:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-Admin123}
      KC_DB: ${KEYCLOAK_DB:-postgres}
      KC_DB_URL: ${KEYCLOAK_DB_URL:-jdbc:postgresql://postgres-test:5432/peerit_test}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME:-testuser}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-testpass}
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_HTTP_RELATIVE_PATH: ${KEYCLOAK_HTTP_RELATIVE_PATH:-/}
    ports:
      - "${KEYCLOAK_PORT:-8080}:8080"
    depends_on:
      postgres-test:
        condition: service_healthy
    command: ["start-dev", "--import-realm"]
    healthcheck:
      test: ["CMD", "bash", "-c", ">/dev/tcp/localhost/8080"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
