# Auth Service Docker Compose
# Run with: docker compose up
# Or from root: docker compose up auth-service

version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peerit-auth-service
    environment:
      # Service Configuration
      - PORT=3020
      - NODE_ENV=development
      
      # Database Configuration (isolated database)
      - DATABASE_URL=postgresql://peerit:peerit_dev@postgres:5432/peerit_auth
      
      # Redis Configuration (dedicated database)
      - REDIS_URL=redis://redis:6379/0
      
      # JWT Configuration
      - JWT_SECRET=auth_service_jwt_secret_change_in_production
      - JWT_EXPIRES_IN=24h
      
      # Email Configuration (for magic links)
      - EMAIL_SERVICE_URL=http://email-service:3026
      
      # Security Configuration
      - BCRYPT_ROUNDS=12
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=5
    ports:
      - "3020:3020"
    networks:
      - peerit-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3020/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

# Import shared infrastructure
networks:
  peerit-network:
    external: true
