name: Build Peerit Keycloak Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
    paths:
      - 'infra/docker/keycloak/**'
  workflow_dispatch:
    inputs:
      keycloak_version:
        description: 'Keycloak base image version'
        required: false
        default: 'latest'
        type: string
      image_tag:
        description: 'Tag for the built image (e.g., v1.0.0, latest)'
        required: false
        default: 'latest'
        type: string
      push_to_registry:
        description: 'Push image to GitHub Container Registry'
        required: false
        default: true
        type: boolean

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: pxl-digital-application-samples/peerit-keycloak

jobs:
  build-keycloak:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Container Registry
        if: ${{ inputs.push_to_registry }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ inputs.image_tag }}
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=tag
            type=ref,event=branch
            type=sha,prefix={{branch}}-
          labels: |
            org.opencontainers.image.title=Peerit Keycloak
            org.opencontainers.image.description=Pre-configured Keycloak for Peerit platform
            org.opencontainers.image.vendor=PXL Digital Application Samples
            org.opencontainers.image.version=${{ inputs.image_tag }}
            
      - name: Build Keycloak image
        uses: docker/build-push-action@v5
        with:
          context: ./infra/docker/keycloak
          file: ./infra/docker/keycloak/Dockerfile
          build-args: |
            KEYCLOAK_VERSION=${{ inputs.keycloak_version || 'latest' }}
          push: ${{ inputs.push_to_registry || github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Generate image summary
        run: |
          echo "## Keycloak Image Built Successfully" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Image Details" >> $GITHUB_STEP_SUMMARY
          echo "- **Base Keycloak Version**: ${{ inputs.keycloak_version || 'latest' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Image Tag**: ${{ inputs.image_tag || github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Registry**: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Pushed to Registry**: ${{ inputs.push_to_registry || github.event_name == 'push' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Trigger**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Features Included" >> $GITHUB_STEP_SUMMARY
          echo "- Pre-configured Peerit realm" >> $GITHUB_STEP_SUMMARY
          echo "- Custom Peerit themes" >> $GITHUB_STEP_SUMMARY
          echo "- PostgreSQL database support (v26+ build)" >> $GITHUB_STEP_SUMMARY
          echo "- Optimized production build" >> $GITHUB_STEP_SUMMARY
          echo "- Multi-platform support (amd64/arm64)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Usage Example" >> $GITHUB_STEP_SUMMARY
          echo '```yaml' >> $GITHUB_STEP_SUMMARY
          echo 'services:' >> $GITHUB_STEP_SUMMARY
          echo '  keycloak:' >> $GITHUB_STEP_SUMMARY
          echo '    image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.image_tag }}' >> $GITHUB_STEP_SUMMARY
          echo '    environment:' >> $GITHUB_STEP_SUMMARY
          echo '      KC_DB: postgres' >> $GITHUB_STEP_SUMMARY
          echo '      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak' >> $GITHUB_STEP_SUMMARY
          echo '      KC_DB_USERNAME: keycloak' >> $GITHUB_STEP_SUMMARY
          echo '      KC_DB_PASSWORD: password' >> $GITHUB_STEP_SUMMARY
          echo '      KC_BOOTSTRAP_ADMIN_USERNAME: admin' >> $GITHUB_STEP_SUMMARY
          echo '      KC_BOOTSTRAP_ADMIN_PASSWORD: admin123' >> $GITHUB_STEP_SUMMARY
          echo '    ports:' >> $GITHUB_STEP_SUMMARY
          echo '      - "8080:8080"' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          
      - name: Test image (if not pushed)
        if: ${{ !inputs.push_to_registry && github.event_name != 'push' }}
        run: |
          echo "Testing built image locally..."
          docker run --rm -d \
            --name test-keycloak \
            -p 8080:8080 \
            -e KC_DB=postgres \
            -e KC_DB_URL=jdbc:postgresql://host.docker.internal:5432/keycloak \
            -e KC_DB_USERNAME=keycloak \
            -e KC_DB_PASSWORD=testpass \
            -e KC_BOOTSTRAP_ADMIN_USERNAME=admin \
            -e KC_BOOTSTRAP_ADMIN_PASSWORD=testpass123 \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.image_tag || 'latest' }}
          
          # Wait for startup
          sleep 60
          
          # Test realm endpoint (v26+ doesn't have /health endpoints)
          curl -f http://localhost:8080/realms/master
          echo "Keycloak master realm accessible"
          
          # Test Peerit realm if it exists
          if curl -f http://localhost:8080/realms/peerit 2>/dev/null; then
            echo "Peerit realm accessible"
          else
            echo "Peerit realm not accessible (expected if no database)"
          fi
          
          # Stop test container
          docker stop test-keycloak
